insert into CFG_PRICING_STRATEGY(ID, PRIORITY, ACTION, AMOUNT) values(SEQU_CFG_PRICING_STRATEGY_ID.nextval, 0, 'set', 50);
insert into CFG_PRICING_STRATEGY(ID, PRIORITY, REFERENCE_METHOD1, REFERENCE_AMOUNT1, REFERENCE_RELATION, REFERENCE_METHOD2, REFERENCE_AMOUNT2, ACTION, AMOUNT)
values(SEQU_CFG_PRICING_STRATEGY_ID.nextval, 1, '>', 250, '&&', '<=', '500', 'mul', 0.8);
insert into CFG_PRICING_STRATEGY(ID, PRIORITY, REFERENCE_METHOD1, REFERENCE_AMOUNT1, REFERENCE_RELATION, REFERENCE_METHOD2, REFERENCE_AMOUNT2, ACTION, AMOUNT)
values(SEQU_CFG_PRICING_STRATEGY_ID.nextval, 1, '>', 500, '&&', '<=', '1000', 'mul', 0.7);

insert into BAS_PLACE(ID, SEQUENCENUMBER, CODE, NAME, SUBJECT, QUALIFIED_CAR_TYPE, ISSUING_AUTHORITY, BRANCH_ADMINISTRATION, ACCEPTANCE_DATE, RESERVATION_MODE, GROUPING_MODE, CREATE_TIME, UPDATE_TIME)
values(SEQU_BAS_PLACE_ID.nextval, NewPlaceSequenceNumber, '00000000', '测试场地', 2, 'C1C2', '发证', '管理部门', '20170101', 1, 1, '20170101090000', '20171128151300');

Insert into CFG_MAPS (ID,SUBJECT,EXAM_ITEM,DRIVER_LICENSE_TYPE,MAPNUMBER,NAME,MEMO) values (SEQU_CFG_MAPS_ID.nextval,'2','20100',null,'1','DC1','倒车入库场地一');
Insert into CFG_MAPS (ID,SUBJECT,EXAM_ITEM,DRIVER_LICENSE_TYPE,MAPNUMBER,NAME,MEMO) values (SEQU_CFG_MAPS_ID.nextval,'2','20300',null,'1','PQ1','坡道起步场地一');
Insert into CFG_MAPS (ID,SUBJECT,EXAM_ITEM,DRIVER_LICENSE_TYPE,MAPNUMBER,NAME,MEMO) values (SEQU_CFG_MAPS_ID.nextval,'2','20400',null,'1','CF1','侧方停车场地一');
Insert into CFG_MAPS (ID,SUBJECT,EXAM_ITEM,DRIVER_LICENSE_TYPE,MAPNUMBER,NAME,MEMO) values (SEQU_CFG_MAPS_ID.nextval,'2','20600',null,'1','QX1','曲线行驶场地一');
Insert into CFG_MAPS (ID,SUBJECT,EXAM_ITEM,DRIVER_LICENSE_TYPE,MAPNUMBER,NAME,MEMO) values (SEQU_CFG_MAPS_ID.nextval,'2','20700',null,'1','ZJ1','直角转弯场地一');
