CREATE OR REPLACE FORCE VIEW BAS_GROUPING_VIEW AS
SELECT  SEQUENCENUMBER,
		(select DICT_NAME from CFG_DICT where DICT_TYPE=1006 and DICT_CODE=SUBJECT) SUBJECT_DICT_NAME,
		EXAM_DATE,
		case when PLACE_ID is null then null else (select SEQUENCENUMBER from BAS_PLACE where ID=PLACE_ID) end PLACE_SEQUENCENUMBER,
		case when PLACE_ID is null then null else (select NAME from BAS_PLACE where ID=PLACE_ID) end PLACE_NAME,
		DRIVER_LICENSE_TYPE,
		(select DICT_NAME from CFG_DICT where DICT_TYPE=1014 and DICT_CODE=EXAM_SESSION) EXAM_SESSION_DICT_NAME,
		case when CAR_ID is null then to_char(null) else (select LICENSE_PLATE from BAS_CAR where ID=CAR_ID) end CAR_LICENSE_NUMBER,
		case when EXAMINER_ID is null then null else (select NAME from BAS_EXAMINER where ID=EXAMINER_ID) end EXAMINER_NAME,
		BRANCH_ADMINISTRATION,
		EXAM_ITEM
FROM BAS_GROUPING;
