CREATE OR REPLACE FORCE VIEW BAS_DRIVING_SCHOOL_VIEW AS
SELECT  SEQUENCENUMBER,
		NAME,
		SHORT_NAME,
		CODE,
		ADDRESS,
		CONTACT_ADDRESS,
		CONTACT,
		CORPORATION,
		REGISTERED_CAPITAL,
		(select DICT_NAME from CFG_DICT where DICT_TYPE=1020 and DICT_CODE=GRADE) GRADE,
		QUALIFIED_CAR_TYPE,
		ISSUING_AUTHORITY,
		(select DICT_NAME from CFG_DICT where DICT_TYPE=1021 and DICT_CODE=STATUS) STATUS,
		AUDITOR,
		CREATE_TIME,
		UPDATE_TIME
FROM BAS_DRIVING_SCHOOL;
