CREATE OR REPLACE FORCE VIEW BUZ_PAYMENT_DETAIL_VIEW AS
SELECT  case when HASH is not null and HASH=GenerateSHA1(TRADE_NO||PAY_TIME||OPERATOR_NAME||OPERATOR_IDNUMBER||STUDENT_IDNUMBER||TIMES||AMOUNT||BOOKING_ID||PRICING_STRATEGY) then 'TRUE' else 'FALSE' end VERIFY,
		TRADE_NO,
		PAY_TIME,
		OPERATOR_NAME,
		OPERATOR_IDNUMBER,
		(select NAME from BAS_STUDENT where IDNUMBER=STUDENT_IDNUMBER) STUDENT_NAME,
		STUDENT_IDNUMBER,
		(select SCHOOL_NAME from BAS_STUDENT where IDNUMBER=STUDENT_IDNUMBER) SCHOOL_NAME,
		(select DICT_NAME from CFG_DICT where DICT_TYPE=1006 and DICT_CODE=SUBJECT) SUBJECT_DICT_NAME,
		(select DICT_NAME from CFG_DICT where DICT_TYPE=1002 and DICT_CODE=FEE_TYPE) FEE_TYPE_DICT_NAME,
		TIMES,
		AMOUNT,
		(select DICT_NAME from CFG_DICT where DICT_TYPE=1001 and DICT_CODE=PAYMENT_WAY) PAYMENT_WAY,
		(select DRIVER_LICENSE_TYPE from BAS_BOOKING where ID=BOOKING_ID) DRIVER_LICENSE_TYPE,
		case when (select CAR_ID from BAS_BOOKING where ID=BOOKING_ID) is null then null else (select LICENSE_PLATE from BAS_CAR where ID=(select CAR_ID from BAS_BOOKING where ID=BOOKING_ID)) end CAR,
		(select BOOKING_DATETIME from BAS_BOOKING where ID=BOOKING_ID) BOOKING_DATETIME,
		PRICING_STRATEGY,
		HASH
FROM BUZ_PAYMENT_DETAIL
order by ID;