CREATE OR REPLACE FORCE VIEW BUZ_SUB2_RECORD_VIEW AS
SELECT	case when JYW is not null and JYW=GenerateSHA1(JDCJSZKSKMDM||JDCJSJNZKZMBH||
		XXJSZMBH||JTGLYWDXSFZMDM||JTGLYWDXSFZMHM||XM||KSYY||JDCJSZZJCXDM||JDCJSZKSKCDM||
		KSCCBH||JDCHPHM||JBR||GLBM||DLR||JDCJSRPXXXDM||KSCS||CZY||KSY1||KSY2||KSCJ||KSQSSJ||
		KSJSSJ||XKXM||ZHPPKF||ZKKF||PDDDKF||CFTCKF||QXXSKF||ZJZWKF||KSCXH||KSZT)
		 then 'TRUE' else 'FALSE' end VERIFY,
        ID,JDCJSZKSKMDM,JDCJSJNZKZMBH,XXJSZMBH,JTGLYWDXSFZMDM,JTGLYWDXSFZMHM,XM,KSYY,JDCJSZZJCXDM,
		JDCJSZKSKCDM,KSCCBH,JDCHPHM,JBR,GLBM,DLR,JDCJSRPXXXDM,KSCS,CZY,KSY1,KSY2,KSCJ,KSQSSJ,
		KSJSSJ,XKXM,ZHPPKF,ZKKF,PDDDKF,CFTCKF,QXXSKF,ZJZWKF,KSCXH,KSZT,		
		JYW
FROM BUZ_SUB2_RECORD
ORDER BY ID;
