CREATE OR REPLACE FORCE VIEW CFG_PRICING_STRATEGY_VIEW AS
SELECT ID,
	PRIORITY,
	(select DICT_NAME from CFG_DICT where DICT_TYPE=1037 and DICT_CODE=ACTION) ACTION_DICT_NAME,
	AMOUNT,
	EFFECTIVE_DATE,
	EXPIRED_DATE,
	START_DATE,
	END_DATE,
	START_TIME,
	END_TIME,
	SCHOOL_NAME,
	STUDENT_IDNUMBER,
	(select DICT_NAME from CFG_DICT where DICT_TYPE=1038 and DICT_CODE=REFERENCE_METHOD1) REFERENCE_METHOD1_DICT_NAME,
	REFERENCE_AMOUNT1,
	case REFERENCE_RELATION when '&&' then '≤¢«“' when '||' then 'ªÚ’ﬂ' end REFERENCE_RELATION_NAME,
	(select DICT_NAME from CFG_DICT where DICT_TYPE=1038 and DICT_CODE=REFERENCE_METHOD2) REFERENCE_METHOD2_DICT_NAME,
	REFERENCE_AMOUNT2
FROM CFG_PRICING_STRATEGY
ORDER by PRIORITY, ID;