create or replace force view STUDENT_SCORE_VIEW as
select 
	--case when HASH is not null and HASH=GenerateSHA1(BUZ_EXAM_INFO.ID||SUBJECT||STUDENT_ID||BOOK_ID||EXAMINER1_ID||EXAMINER2_ID||PLACE_ID||CAR_ID||EXAM_START_TIME||EXAM_END_TIME||CURRENT_EXAM_TIMES||CURRENT_EXAM_SCORE||EXAM_STATUS||CONTRAIL_PATH||VIDEO_PATH) then 'TRUE' else 'FALSE' end VERIFY,
	BAS_STUDENT.ID STUDENT_ID,
	BUZ_EXAM_INFO.ID EXAM_ID,
	BAS_BOOKING.ID,
	NAME,
	IDNUMBER,
	PHOTO1,
	EXAMNUMBER,
	BAS_BOOKING.DRIVER_LICENSE_TYPE,
	(select DICT_NAME from CFG_DICT where DICT_TYPE=1007 and DICT_CODE=EXAM_REASON) EXAM_REASON_DICT_NAME,
	BAS_BOOKING.SUBJECT,
	BAS_BOOKING.SEQUENCENUMBER,
	(select NAME from BAS_PLACE where ID=BAS_BOOKING.PLACE_ID) PLACE_NAME,
	(select NAME from BAS_EXAMINER where ID=BAS_BOOKING.EXAMINER1_ID) EXAMINER1,
	(select NAME from BAS_EXAMINER where ID=BAS_BOOKING.EXAMINER2_ID) EXAMINER2,
	(select SEQUENCENUMBER from BAS_CAR where ID=BAS_BOOKING.CAR_ID) CAR_SEQUENCENUMBER,
	CURRENT_EXAM_SCORE,
	substr(EXAM_START_TIME, 1, 8) EXAM_DATE,
	substr(EXAM_START_TIME,	9, 6) EXAM_TIME,
	BOOKING_TIMES,
	CURRENT_EXAM_TIMES,
	(select DICT_NAME from CFG_DICT where DICT_TYPE=1008 and DICT_CODE=BUZ_EXAM_INFO.EXAM_STATUS) STATUS_DICT_NAME
from BAS_STUDENT left join BAS_BOOKING on BAS_STUDENT.ID=BAS_BOOKING.STUDENT_ID left join BUZ_EXAM_INFO on BAS_BOOKING.ID=BUZ_EXAM_INFO.BOOKING_ID
where BUZ_EXAM_INFO.ID is not null
--    and BUZ_EXAM_INFO.EXAM_STATUS>0
order by EXAM_ID desc;