CREATE OR REPLACE FORCE VIEW SYS_ROLE_PERMISSION_VIEW AS
SELECT	ROLE_ID,
		(select NAME from SYS_ROLE where ID=ROLE_ID) ROLE_NAME,
		PERMISSION_CODE,
		(select NAME from SYS_PERMISSION where CODE=PERMISSION_CODE) PERMISSION_NAME,
		(select IS_ADMIN from SYS_PERMISSION where CODE=PERMISSION_CODE) IS_ADMIN,
        (select IS_POLICE from SYS_PERMISSION where CODE=PERMISSION_CODE) IS_POLICE
FROM SYS_ROLE_PERMISSION;
