CREATE TABLE BUZ_SUB2_RECORD 
(
  ID NUMBER NOT NULL 
, SUBJECT VARCHAR2(1 BYTE) NOT NULL 
, EXAMNUMBER VARCHAR2(12 BYTE) 
, STUDY_NUMBER VARCHAR2(12 BYTE) 
, IDTYPE VARCHAR2(3 BYTE) NOT NULL 
, IDNUMBER VARCHAR2(18 BYTE) NOT NULL 
, STUDENT_NAME VARCHAR2(50 BYTE) NOT NULL 
, EXAM_REASON VARCHAR2(1 BYTE) DEFAULT 'A' NOT NULL 
, DRIVER_LICENSE_TYPE VARCHAR2(2 BYTE) NOT NULL 
, PLACE_CODE VARCHAR2(8 BYTE) NOT NULL 
, EXAM_SESSION NUMBER(2, 0) 
, LICENSE_PLATE VARCHAR2(15 BYTE) 
, OPERATOR_NAME VARCHAR2(30 BYTE) NOT NULL 
, BRANCH_ADMINISTRATION VARCHAR2(2010 BYTE) NOT NULL 
, SCHOOL_CODE VARCHAR2(64 BYTE) 
, SCHOOL_NAME VARCHAR2(64 BYTE) 
, EXAM_TIMES NUMBER(2, 0) 
, SYSTEM_OPERATOR VARCHAR2(30 BYTE) 
, EXAMINER1 VARCHAR2(30 BYTE) 
, EXAMINER2 VARCHAR2(30 BYTE) 
, SCORE NUMBER(3, 0) 
, EXAM_START_TIME VARCHAR2(14 BYTE) 
, EXAM_END_TIME VARCHAR2(14 BYTE) 
, OPTIONAL_ITEM VARCHAR2(64 BYTE) 
, DEDUCT_SCORE_ZH NUMBER(3, 0) 
, DEDUCT_SCORE_DK_ZK NUMBER(3, 0) 
, DEDUCT_SCORE_PQ NUMBER(3, 0) 
, DEDUCT_SCORE_CF NUMBER(3, 0) 
, DEDUCT_SCORE_DB NUMBER(3, 0) 
, DEDUCT_SCORE_QX NUMBER(3, 0) 
, DEDUCT_SCORE_ZJ NUMBER(3, 0) 
, DEDUCT_SCORE_XK NUMBER(3, 0) 
, DEDUCT_SCORE_ZA NUMBER(3, 0) 
, DEDUCT_SCORE_QF NUMBER(3, 0) 
, DEDUCT_SCORE_DT NUMBER(3, 0) 
, DEDUCT_SCORE_GS NUMBER(3, 0) 
, DEDUCT_SCORE_SQ NUMBER(3, 0) 
, DEDUCT_SCORE_SD NUMBER(3, 0) 
, DEDUCT_SCORE_YW NUMBER(3, 0) 
, DEDUCT_SCORE_SH NUMBER(3, 0) 
, DEDUCT_SCORE_JJ NUMBER(3, 0) 
, LOCAL_ITEM1 VARCHAR2(30 BYTE) 
, LOCAL_ITEM2 VARCHAR2(30 BYTE) 
, LOCAL_ITEM3 VARCHAR2(30 BYTE) 
, DEDUCT_SCORE_LI1 NUMBER(3, 0) 
, DEDUCT_SCORE_LI2 NUMBER(3, 0) 
, DEDUCT_SCORE_LI3 NUMBER(3, 0) 
, HASHCODE VARCHAR2(256 BYTE) NOT NULL 
, CAR_SERIALNUMBER VARCHAR2(8 BYTE) NOT NULL 
, EXAM_STATUS VARCHAR2(1 BYTE) 
, CONSTRAINT BUZ_SUB2_RECORD_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX BUZ_SUB2_RECORD_PK ON BUZ_SUB2_RECORD (ID ASC) 
      LOGGING 
      TABLESPACE TNZCDATA 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE TNZCDATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

COMMENT ON COLUMN BUZ_SUB2_RECORD.ID IS '主键';

COMMENT ON COLUMN BUZ_SUB2_RECORD.SUBJECT IS '考试科目(字典【1006】)';

COMMENT ON COLUMN BUZ_SUB2_RECORD.EXAMNUMBER IS '准考证明编号';

COMMENT ON COLUMN BUZ_SUB2_RECORD.STUDY_NUMBER IS '学习驾驶证明编号';

COMMENT ON COLUMN BUZ_SUB2_RECORD.IDTYPE IS '学员身份证明类型(字典【2002】)';

COMMENT ON COLUMN BUZ_SUB2_RECORD.IDNUMBER IS '身份证明号码';

COMMENT ON COLUMN BUZ_SUB2_RECORD.STUDENT_NAME IS '姓名';

COMMENT ON COLUMN BUZ_SUB2_RECORD.EXAM_REASON IS '考试原因(字典【1007】)';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DRIVER_LICENSE_TYPE IS '驾驶证类型/考试车型(字典【2003】)';

COMMENT ON COLUMN BUZ_SUB2_RECORD.PLACE_CODE IS '考场代码';

COMMENT ON COLUMN BUZ_SUB2_RECORD.EXAM_SESSION IS '考试场次(字典【1014】)';

COMMENT ON COLUMN BUZ_SUB2_RECORD.LICENSE_PLATE IS '考试车辆号牌号码';

COMMENT ON COLUMN BUZ_SUB2_RECORD.OPERATOR_NAME IS '经办人';

COMMENT ON COLUMN BUZ_SUB2_RECORD.BRANCH_ADMINISTRATION IS '管理部门';

COMMENT ON COLUMN BUZ_SUB2_RECORD.SCHOOL_CODE IS '代理人（驾校代码）';

COMMENT ON COLUMN BUZ_SUB2_RECORD.SCHOOL_NAME IS '驾校名称';

COMMENT ON COLUMN BUZ_SUB2_RECORD.EXAM_TIMES IS '考试次数';

COMMENT ON COLUMN BUZ_SUB2_RECORD.SYSTEM_OPERATOR IS '操作员';

COMMENT ON COLUMN BUZ_SUB2_RECORD.EXAMINER1 IS '考试员1';

COMMENT ON COLUMN BUZ_SUB2_RECORD.EXAMINER2 IS '考试员2';

COMMENT ON COLUMN BUZ_SUB2_RECORD.SCORE IS '考试成绩';

COMMENT ON COLUMN BUZ_SUB2_RECORD.EXAM_START_TIME IS '考试起始时间(格式:yyyymmddhhmmss)';

COMMENT ON COLUMN BUZ_SUB2_RECORD.EXAM_END_TIME IS '考试结束时间(格式:yyyymmddhhmmss)';

COMMENT ON COLUMN BUZ_SUB2_RECORD.OPTIONAL_ITEM IS '选考项目';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_ZH IS '综合评判扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_DK_ZK IS '倒车入库或桩考扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_PQ IS '坡道定点停车和起步扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_CF IS '侧方停车扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_DB IS '通过单边桥扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_QX IS '曲线行驶扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_ZJ IS '直角转弯扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_XK IS '通过限宽门扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_ZA IS '通过连续障碍扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_QF IS '起伏路行驶扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_DT IS '窄路调头扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_GS IS '模拟高速公路行驶扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_SQ IS '模拟连续急弯山区路行驶扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_SD IS '模拟隧道行驶扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_YW IS '模拟雨(雾）天行驶扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_SH IS '模拟湿滑路行驶扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_JJ IS '模拟紧急情况处置扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.LOCAL_ITEM1 IS '地方自选项目1';

COMMENT ON COLUMN BUZ_SUB2_RECORD.LOCAL_ITEM2 IS '地方自选项目2';

COMMENT ON COLUMN BUZ_SUB2_RECORD.LOCAL_ITEM3 IS '地方自选项目3';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_LI1 IS '地方自选项目1扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_LI2 IS '地方自选项目2扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.DEDUCT_SCORE_LI3 IS '地方自选项目3扣分';

COMMENT ON COLUMN BUZ_SUB2_RECORD.HASHCODE IS '效验位';

COMMENT ON COLUMN BUZ_SUB2_RECORD.CAR_SERIALNUMBER IS '考试车辆备案序号';

COMMENT ON COLUMN BUZ_SUB2_RECORD.EXAM_STATUS IS '考试状态(字典【1008】)';
