INSERT INTO CFG_PARAM(ID,SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, IS_ADMIN_PARAM, MEMO)
VALUES(SEQU_CFG_PARAM_ID.NEXTVAL, 0, 0, 'WX_APPID', '公众账号ID', 'CHAR', 'CAE0401154685B038AA8448E995BADBE4B7E2BBB7C129D4A', 0, '微信支付分配的公众账号ID');
INSERT INTO CFG_PARAM(ID,SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, IS_ADMIN_PARAM, MEMO)
VALUES(SEQU_CFG_PARAM_ID.NEXTVAL, 0, 0, 'WX_MCHID', '商户号', 'CHAR', 'A79A3A65ADA1DA87937867AB50A72C9A', 0, '微信支付分配的商户号');
INSERT INTO CFG_PARAM(ID,SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, IS_ADMIN_PARAM, MEMO)
VALUES(SEQU_CFG_PARAM_ID.NEXTVAL, 0, 0, 'WX_NOTIFY_URL', '通知地址', 'CHAR', '17098EB74D2F6020182BAF18D5E25699', 0, '异步接收微信支付结果通知的回调地址,通知url必须为外网可访问的url,不能携带参数.');
INSERT INTO CFG_PARAM(ID,SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, IS_ADMIN_PARAM, MEMO)
VALUES(SEQU_CFG_PARAM_ID.NEXTVAL, 0, 0, 'WX_KEYID', '安全密钥', 'CHAR', '2D592BE9AC07E9134F9D5CEF97CD84E3EC3D2F784AFC60E6FE994594352E27F3', 0, '商户平台设置的密钥key');
INSERT INTO CFG_PARAM(ID,SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, IS_ADMIN_PARAM, MEMO)
VALUES(SEQU_CFG_PARAM_ID.NEXTVAL, 1, 0, 'MODE_SIMULATION', '模考模式计费类型', 'CHAR', 'COUNT', 0, '模拟考试模式下按计时/次收费');
INSERT INTO CFG_PARAM(ID,SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, IS_ADMIN_PARAM, MEMO)
VALUES(SEQU_CFG_PARAM_ID.NEXTVAL, 1, 0, 'MODE_PRACTICE', '练习模式计费类型', 'CHAR', 'HOUR', 0, '练习考试模式下按计时/次收费');
INSERT INTO CFG_PARAM(ID,SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, IS_ADMIN_PARAM, MEMO)
VALUES(SEQU_CFG_PARAM_ID.NEXTVAL, 1, 0, 'PAY_WAITTIME', '支付等待时间', 'INT', '30', 0, '计时单位:秒');
INSERT INTO CFG_PARAM(ID,SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, IS_ADMIN_PARAM, MEMO)
VALUES(SEQU_CFG_PARAM_ID.NEXTVAL, 1, 0, 'CAR_ENABLED_PAY', '车载是否启用支付功能', 'BOOL', '0', 0, '0为关闭;1为启用');
INSERT INTO CFG_PARAM(ID,SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, IS_ADMIN_PARAM, MEMO)
VALUES(SEQU_CFG_PARAM_ID.NEXTVAL, 1, 0, 'CAR_ENABLED_FINGER', '车载是否启用指纹识别功能', 'BOOL', '0', 0, '0为关闭(关闭状态下使用密码识别);1为启用');
INSERT INTO CFG_PARAM(ID,SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, IS_ADMIN_PARAM, MEMO)
VALUES(SEQU_CFG_PARAM_ID.NEXTVAL, 1, 0, 'CAR_ENABLED_CAPTUREPIC', '车载是否启用抓拍功能', 'BOOL', '0', 0, '0为关闭(关闭状态下使用密码识别);1为启用');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 0, 'SERVICE_URL', '服务URL', 'CHAR', 'http://192.168.1.254:9080/monweb/services/TmriOutAccess?wsdl', '公安网服务接口地址');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 0, 'SERVICE_SERIAL_NUMBER', '服务接口序列号', 'CHAR', '7F1C0909020517040F158EDD82D08B8D8F8AF3E0FD8D9AEBF296A7A6D299DDDD32', '公安网服务接口序列号');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 0, 'PLACE_SERIAL_NUMBER', '考场序号', 'CHAR', '32000899', '当前考场序列号');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 0, 'PLACE_CODE', '考场代码', 'CHAR', '3202810219', '考场代码（考试地点）');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 0, 'SYSTEM_SERIAL_NUMBER', '考试系统编号', 'CHAR', '32000002', '考试系统备案编号');


insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, 'DEFAULT_USER_MAX_FAILURE_COUNT', '默认用户最大连续失败登录次数', 'INT', '3', '');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, 'DEFAULT_TERMINAL_MAX_FAILURE_COUNT', '默认终端最大连续失败登录次数', 'INT', '10', '');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, 'DEFAULT_USER_PASSWORD', '默认用户密码', 'CHAR', 'defPwd#123', '');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, 'PASSWORD_VALID_PERIOD', '默认用户密码有效期（天）', 'INT', '90', '');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, 'TERMINAL_LOCK_DURATION', '默认终端锁定时间（分钟）', 'INT', '60', '');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, 'LOGIN_TIMEOUT', '登录超时时间（分钟）', 'INT', '10', '');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 1, 0, 'AUTO_UPGRADE', '车载端是否自动更新', 'BOOL', '1', '0为关闭；1为启用');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, 'BOOKING_DATE_LIMIT', '预约日期限制', 'INT', '1', '1为当天；2为2天之内；3为3天之内；依此类推');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '000000', '00:00:00', 'BOOL', 'FALSE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '010000', '01:00:00', 'BOOL', 'FALSE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '020000', '02:00:00', 'BOOL', 'FALSE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '030000', '03:00:00', 'BOOL', 'FALSE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '040000', '04:00:00', 'BOOL', 'FALSE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '050000', '05:00:00', 'BOOL', 'FALSE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '060000', '06:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '070000', '07:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '080000', '08:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '090000', '09:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '100000', '10:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '110000', '11:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '120000', '12:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '130000', '13:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '140000', '14:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '150000', '15:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '160000', '16:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '170000', '17:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '180000', '18:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '190000', '19:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '200000', '20:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '210000', '21:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '220000', '22:00:00', 'BOOL', 'TRUE', 'TRUE当前时段可用；FALSE当前时段不可用');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, '230000', '23:00:00', 'BOOL', 'FALSE', 'TRUE当前时段可用；FALSE当前时段不可用');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, 'DATABASE_VERSION', '数据库版本', 'CHAR', '1.0.0.2', '主版本.次版本.分支版本.发布版本，分支版本0表示通用版本');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 1, 1, 'VEHICLE_VERSION', '车载程序版本', 'CHAR', '1.0.1013.2', '主版本.次版本.分支版本.发布版本，分支版本0表示通用版本');

insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, 'CAR_ALLOCATION_INTERVAL', '刷新时间（秒）', 'INT', '1', '分车程序车辆状态刷新时间间隔');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, 'CAR_ALLOCATION_PROJECT_ADDRESS', '投显地址', 'CHAR', '192.168.1.100', '分车程序投显终端地址');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, 'CAR_ALLOCATION_PROJECT_PORT', '投显端口', 'INT', '5678', '分车程序投显终端端口');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, 'CAR_ALLOCATION_PROJECT_COUNT', '投显数量', 'INT', '10', '分车程序投显学员数量');
insert into CFG_PARAM(ID, SUBSYS_ID, PARAM_GRADE, PARAM_NAME, DISPLAY_NAME, PARAM_TYPE, PARAM_VALUE, MEMO)
values(SEQU_CFG_PARAM_ID.nextval, 2, 1, 'CAR_ALLOCATION_WAITING_TIMEOUT', '等候超时（分钟）', 'INT', '10', '已分车学员上车等待时间，过号重排时间');

commit;