/*************************************************
*字典种类: 10~19-业务字典类型 20~29-G(A/B)/T标准字典类型 30~39-扩展字典类型
* 10~19-业务字典类型
* ——1001-支付类型
* ——1002-收费类型
* ——1003-参数级别类型
* ——1004-是或否标识符类型，取消
* ——1005-交易状态类型
* ——1006-考试科目类型
* ——1007-考试原因类型
* ——1008-考试状态类型
* ——1009-考场预约类型
* ——1010-用户身份类型
* ——1011-用户锁标识类型
* ——1012-用户启用/失效标识类型
* ——1013-用户状态类型
* ——1014-考试场次类型
* ——1015-考试员状态类型
* ——1016-考试车/场地使用状态类型
* ——1017-考试预约模式类型
* ——1018-考试分组模式类型
* ——1019-评判方式类型
* ——1020-驾校级别类型
* ——1021-驾校状态类型
* ——1022-设备状态类型
* ——1023-排队状态类型
* ——1024-考试过程标识类型
* ——1025-考试过程类型
* ——1026-考试项目结束操作记录类型
* ——1027-支付折扣类型
* ——1028-日志操作行为类型
* ——1029-日志操作结果类型
* ——1030-设备参数数据类型
* ——1031-学员签到类型
* ——1032-暂停考生异常类型
* ——1033-暂停考场异常类型
* ——1034-异常过程处理类型
* ——1035-付费学习状态类型
* ——1036-学员状态类型
* ——1037-定价行为
* ——1038-定价参考方法
* ——1039-权限分类
*
* 20~29-G(A/B)/T标准字典类型
* ——2001-性别类型
* ——2002-身份证明类型
* ——2003-驾驶证类型
* ——2004-车辆类型代码类型
* ——2005-机动车状态代码类型
* ——2006-机动车号牌种类代码类型
*
* 30~39-扩展字典类型
* ——3001-身份信息比对返回值类型
* ——3002-考试项目开始返回值类型
* ——3003-考试扣分返回值类型
* ——3004-考试过程图片返回值类型
* ——3005-考试项目结束返回值类型
* ——3006-考试科目考试结束返回值类型
*
**************************************************/

--*字典种类:
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '0', '字典类型', -1, '定义字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 0, '10~19', '业务字典类型', 1, '字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 0, '20~29', 'G(A/B)/T标准字典类型', 2, '字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 0, '30~39', '扩展字典类型', 3, '字典类型');  
COMMIT;

-->>>>-业务字典类型/////////////////////////////////////////////////////////
--1001-支付类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1001', '支付类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1001, 'WXPAY', '微信支付', 1, '支付类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1001, 'ALIPAY', '支付宝支付', 2, '支付类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1001, 'UNIONPAY', '银联卡支付', 3, '支付类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1001, 'OTHERPAY', '其他支付', 4, '支付类型');
COMMIT;

--1002-收费类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1002', '收费类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1002, 'HOUR', '计时', 1, '收费类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1002, 'COUNT', '计次', 2, '收费类型');
COMMIT;

--1003-参数级别类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1003', '参数级别类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1003, '0', '公共参数', 1, '参数级别类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1003, '1', '后台参数', 2, '参数级别类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1003, '2', '其他参数', 3, '参数级别类型');
COMMIT;

--1005-交易状态类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1005', '支付状态类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1005, 'SUCCESS', '支付成功', 1, '支付状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1005, 'FAIL', '支付失败', 2, '支付状态类型');
COMMIT;

--1006-考试科目类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1006', '考试科目类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1006, '1', '科目一', 1, '考试科目类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1006, '2', '科目二', 2, '考试科目类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1006, '3', '科目三', 3, '考试科目类型');
COMMIT;

--1007-考试原因类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1007', '考试原因类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1007, 'A', '初领', 1, '考试原因类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1007, 'B', '增驾', 2, '考试原因类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1007, 'C', '满分学习', 3, '考试原因类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1007, 'D', '补考', 4, '考试原因类型');
COMMIT;

--1008-考试状态类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1008', '考试状态类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1008, '0', '考试中', 1, '考试状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1008, '1', '合格', 2, '考试状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1008, '2', '不合格', 3, '考试状态类型');
COMMIT;

--1009-考场预约类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1009', '考场预约类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1009, '0', '未预约', 1, '考场预约类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1009, '1', '已预约', 2, '考场预约类型');
COMMIT;

--1010-用户身份类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1010', '用户身份类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1010, '0', '非警员', 1, '用户身份类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1010, '1', '警员', 2, '用户身份类型');
COMMIT;

--1011-用户锁标识类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1011', '用户锁标识类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1011, '0', '未锁定', 1, '用户锁标识类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1011, '1', '锁定', 2, '用户锁标识类型');
COMMIT;

--1012-用户启用/失效标识类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1012', '用户启用/失效标识类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1012, '0', '启用', 1, '用户启用/失效标识类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1012, '1', '停用', 2, '用户启用/失效标识类型');
COMMIT;

--1013-用户状态类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1013', '用户状态类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1013, '0', '未登录', 1, '用户状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1013, '1', '已登录', 2, '用户状态类型');
  INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1013, '2', '已删除', 3, '用户状态类型');

--1014-考试场次类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1014', '考试场次类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1014, '0', '上午场', 1, '考试场次类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1014, '1', '下午场', 2, '考试场次类型');
COMMIT;

--1015-考试员状态类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1015', '考试员状态类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1015, 'A', '正常', 1, '考试员状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1015, 'B', '过期', 2, '考试员状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1015, 'C', '注销', 3, '考试员状态类型');
COMMIT;

--1016-考试车/场地使用状态类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1016', '考试车/场地使用状态类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1016, 'A', '正常', 1, '考试车/场地使用状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1016, 'B', '暂停考试', 2, '考试车/场地使用状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1016, 'C', '取消考试', 3, '考试车/场地使用状态类型');
COMMIT;

--1017-考试预约模式类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1017', '考试预约模式类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1017, '1', '一次预约', 1, '考试预约模式类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1017, '2', '两次预约', 2, '考试预约模式类型');
COMMIT;

--1018-考试分组模式类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1018', '考试分组模式类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1018, '1', '按学员分组', 1, '考试分组模式类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1018, '2', '按教练车分组', 2, '考试分组模式类型');
COMMIT;

--1019-评判方式类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1019', '评判方式类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1019, '0', '人工评判', 1, '评判方式类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1019, '1', '自动评判', 2, '评判方式类型');
COMMIT;

--1020-驾校级别类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1020', '驾校级别类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1020, '0', '其他', 1, '驾校级别类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1020, '1', '一级', 2, '驾校级别类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1020, '2', '二级', 3, '驾校级别类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1020, '3', '三级', 4, '驾校级别类型');
COMMIT;

--1021-驾校状态类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1021', '驾校状态类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1021, 'A', '正常', 1, '驾校状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1021, 'B', '暂停受理', 2, '驾校状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1021, 'C', '取消资格', 3, '驾校状态类型');
COMMIT;

--1022-设备状态类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1022', '设备状态类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1022, 'A', '正常', 1, '设备状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1022, 'B', '故障', 2, '设备状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1022, 'C', '暂停考试', 3, '设备状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1022, 'D', '报废', 4, '设备状态类型');
COMMIT;

--1023-排队状态类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1023', '排队状态类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1023, '0', '正在考试', 1, '排队状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1023, '1', '备考', 2, '排队状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1023, '2', '侯考', 3, '排队状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1023, '3', '考试结束', 4, '排队状态类型');
COMMIT;

--1024-考试过程标识类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1024', '考试过程标识类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1024, 'SS', '科目开始', 1, '考试过程标识类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1024, 'PP', '项目过程', 2, '考试过程标识类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1024, 'SE', '科目结束', 3, '考试过程标识类型');
COMMIT;

--1025-考试过程类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1025', '考试过程类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1025, 'C51', '身份认证', 1, '考试过程类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1025, 'C52', '考试项目开始', 2, '考试过程类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1025, 'C53', '扣分', 3, '考试过程类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1025, 'C54', '拍照', 4, '考试过程类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1025, 'C55', '考试项目结束', 5, '考试过程类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1025, 'C56', '考试科目结束', 6, '考试过程类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1025, 'C57', '打印成绩单', 7, '考试过程类型');
COMMIT;

--1026-考试项目结束操作记录类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1026', '考试项目结束操作记录类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1026, '0', '撤销该考试项目记录', 1, '考试项目结束操作记录类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1026, '1', '正常', 2, '考试项目结束操作记录类型');
COMMIT;

--1027-支付折扣类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1027', '支付折扣类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1027, '0', '折扣优惠', 1, '支付折扣类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1027, '1', '立减金额优惠', 2, '支付折扣类型');
COMMIT;

--1028-日志操作行为类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1028', '日志操作行为类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1028, 'LOGIN', '登录', 1, '日志操作行为类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1028, 'ENTER', '进入', 2, '日志操作行为类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1028, 'LEAVE', '离开', 3, '日志操作行为类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1028, 'APPEND', '增加', 4, '日志操作行为类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1028, 'DELETE', '删除', 5, '日志操作行为类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1028, 'UPDATE', '修改', 6, '日志操作行为类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1028, 'SELECT', '查看', 7, '日志操作行为类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1028, 'BOOK', '预约', 8, '日志操作行为类型');
COMMIT;

--1029-日志操作结果类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1029', '日志操作结果类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1029, '0', '失败', 1, '日志操作结果类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1029, '1', '成功', 2, '日志操作结果类型');
COMMIT;

--1030-设备归属类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1030', '设备归属类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1030, 'C', '车辆设备', 1, '设备归属类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1030, 'M', '场地设备', 2, '设备归属类型');
COMMIT;

--1031-学员签到类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1031', '学员签到类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1031, '0', '未签到', 1, '学员签到类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1031, '1', '已签到', 2, '学员签到类型');
COMMIT;

--1032-暂停考生异常类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1032', '暂停考生异常类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1032, '1', '暂停考试', 1, '暂停考生异常类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1032, '2', '设备异常重考', 2, '暂停考生异常类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1032, '3', '成绩不合格', 3, '暂停考生异常类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1032, '4', '考试恢复', 4, '暂停考生异常类型');
COMMIT;

--1033-暂停考场异常类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1033', '暂停考场异常类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1033, '5', '考场无视频信号', 1, '暂停考场异常类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1033, '6', '考试车无视频信号', 2, '暂停考场异常类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1033, '7', '遮挡摄像头', 3, '暂停考场异常类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1033, '8', '考试舞弊', 4, '暂停考场异常类型');
COMMIT;

--1034-异常过程处理类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1034', '异常过程处理类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1034, '1', '暂停考生异常', 1, '异常过程处理类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1034, '2', '暂停考场异常', 2, '异常过程处理类型');
COMMIT;

--1035-付费学习状态类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1035', '付费学习状态类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1035, '1', '未完成', 1, '付费学习状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1035, '2', '已完成', 2, '付费学习状态类型');
COMMIT;

--1036-学员状态类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1036', '学员状态类型', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1036, '0', '在学习', 1, '学员状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1036, '1', '学习终止', 2, '学员状态类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1036, '2', '学习暂停', 3, '学员状态类型');
COMMIT;

--1037-定价行为
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1037', '定价行为', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1037, 'set', '设定', 1, '定价行为');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1037, 'add', '增加', 2, '定价行为');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1037, 'sub', '扣减', 3, '定价行为');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1037, 'mul', '乘以', 4, '定价行为');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1037, 'div', '除以', 5, '定价行为');
COMMIT;

--1038-定价参考方法
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1038', '定价参考方法', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1038, '>', '大于', 1, '定价参考方法');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1038, '=', '等于', 2, '定价参考方法');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1038, '<', '小于', 3, '定价参考方法');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1038, '>=', '不小于', 4, '定价参考方法');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1038, '<=', '不大于', 5, '定价参考方法');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1038, '<>', '不等于', 6, '定价参考方法');
COMMIT;

--1039-权限分类
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '1039', '权限分类', -1, '业务字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1039, 'BUSINESS', '业务办理', 1, '权限分类');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1039, 'SYSTEM', '系统管理', 2, '权限分类');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1039, 'SECURITY', '安全管理', 3, '权限分类');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 1039, 'AUDIT', '审计管理', 4, '权限分类');

  
--<<<<-业务字典类型/////////////////////////////////////////////////////////

-->>>>-20~29-G(A/B)/T标准字典类型///////////////////////////////////////////////
--2001-性别类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '2001', '性别类型', -1, 'G(A/B)/T标准字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2001, '0', '未知性别', 1, '性别类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2001, '1', '男性', 2, '性别类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2001, '2', '女性', 3, '性别类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2001, '9', '未说明性别', 4, '性别类型');
COMMIT;

--2002-身份证明类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '2002', '身份证明类型', -1, 'G(A/B)/T标准字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2002, 'A', '居民身份证', 1, '身份证明类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2002, 'B', '组织机构代码证书', 2, '身份证明类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2002, 'C', '军官证', 3, '身份证明类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2002, 'D', '士兵证', 4, '身份证明类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2002, 'E', '军官离退休证', 5, '身份证明类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2002, 'F', '境外人员身份证明', 6, '身份证明类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2002, 'G', '外交人员身份证件', 7, '身份证明类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2002, 'H', '居民户口簿', 8, '身份证明类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2002, 'J', '单位注销证明', 9, '身份证明类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2002, 'K', '居住暂住证明', 10, '身份证明类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2002, 'L', '驻华机构证明', 11, '身份证明类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2002, 'Z', '其他证件', 12, '身份证明类型');
COMMIT;

--2003-驾驶证类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '2003', '驾驶证类型', -1, 'G(A/B)/T标准字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'A1', '大型载客汽车', 1, '驾驶证类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'A2', '牵引车，重型、中型全挂、半挂汽车列车', 2, '驾驶证类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'A3', '核载10人以上的城市公共汽车', 3, '驾驶证类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'B1', '重型载客汽车', 4, '驾驶证类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'B2', '重型、中型载货汽车', 5, '驾驶证类型'); 
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'C1', '小型、微型载客汽车', 6, '驾驶证类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'C2', '小型、微型自动挡载客汽车', 7, '驾驶证类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'C3', '低速载货汽车', 8, '驾驶证类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'C4', '三轮汽车', 9, '驾驶证类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'D', '发动机排量大于50ml的三轮摩托车', 10, '驾驶证类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'E', '发动机排量大于50ml的二轮摩托车', 11, '驾驶证类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'F', '发动机排量小于等于50ml的摩托车', 12, '驾驶证类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'M', '轮式自行机械车', 13, '驾驶证类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'N', '无轨电车', 14, '驾驶证类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2003, 'P', '有轨电车', 15, '驾驶证类型');   
COMMIT;

--2004-车辆类型代码类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '2004', '车辆类型代码类型', -1, 'G(A/B)/T标准字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K10', '大型客车', 1, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K11', '大型普通客车', 2, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K12', '大型双层客车', 3, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K13', '大型卧铺客车', 4, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K14', '大型铰接客车', 5, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K15', '大型越野客车', 6, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K16', '大型轿车', 7, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K17', '大型专用客车', 8, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K20', '中型客车', 9, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K21', '中型普通客车', 10, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K22', '中型双层客车', 11, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K23', '中型卧铺客车', 12, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K24', '中型铰接客车', 13, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K25', '中型越野客车', 14, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K27', '中型专用客车', 15, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K30', '小型客车', 16, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K31', '小型普通客车', 17, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K32', '小型越野客车', 18, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K33', '小型轿车', 19, '车辆类型代码类型'); 
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K34', '小型专用客车', 20, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K40', '微型客车', 21, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K41', '微型普通客车', 22, '车辆类型代码类型');    
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K42', '微型越野客车', 23, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'K43', '微型轿车', 24, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H10', '重型货车', 25, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H11', '重型普通货车', 26, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H12', '重型厢式货车', 27, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H13', '重型封闭货车', 28, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H14', '重型罐式货车', 29, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H15', '重型平板货车', 30, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H16', '重型集装货车', 31, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H17', '重型自卸货车', 32, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H18', '重型特殊结构货车', 33, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H19', '重型仓栅式货车', 34, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H20', '中型货车', 35, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H21', '中型普通货车', 36, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H22', '中型厢式货车', 37, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H23', '中型封闭货车', 38, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H24', '中型罐式货车', 39, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H25', '中型平板货车', 40, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H26', '中型集装货车', 41, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H27', '中型自卸货车', 42, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H28', '中型特殊结构货车', 43, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H29', '中型仓栅式货车', 44, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H30', '轻型货车', 45, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H31', '轻型普通货车', 46, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H32', '轻型厢式货车', 47, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H33', '轻型封闭货车', 48, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H34', '轻型罐式货车', 49, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H35', '轻型平板货车', 50, '车辆类型代码类型');
COMMIT;
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H37', '轻型自卸货车', 51, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H38', '轻型特殊结构货车', 52, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H39', '轻型仓栅式货车', 53, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H40', '微型货车', 54, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H41', '微型普通货车', 55, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H42', '微型厢式货车', 56, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H43', '微型封闭货车', 57, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H44', '微型罐式货车', 58, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H45', '微型自卸货车', 59, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H46', '微型特殊结构货车', 60, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H47', '微型仓栅式货车', 61, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H50', '低速货车', 62, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H51', '普通低速货车', 63, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H52', '厢式低速货车', 64, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H53', '罐式低速货车', 65, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H54', '自卸低速货车', 66, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'H55', '仓栅式低速货车', 67, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'Q10', '重型牵引车', 68, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'Q11', '重型半挂牵引车', 69, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'Q12', '重型全挂牵引车', 70, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'Q30', '轻型牵引车', 71, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'Q31', '轻型半挂牵引车', 72, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'Q32', '轻型全挂牵引车', 73, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'Z11', '大型专项作业车', 74, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'Z21', '中型专项作业车', 75, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'Z31', '小型专项作业车', 76, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'Z41', '微型专项作业车', 77, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'Z51', '重型专项作业车', 78, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'Z71', '轻型专项作业车', 79, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'D11', '无轨电车', 80, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'D12', '有轨电车', 81, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'M10', '三轮摩托车', 82, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'M11', '普通正三轮摩托车', 83, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'M12', '轻便正三轮摩托车', 84, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'M13', '正三轮载客摩托车', 85, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'M14', '正三轮载货摩托车', 86, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'M15', '侧三轮摩托车', 87, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'M20', '二轮摩托车', 88, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'M21', '普通二轮摩托车', 89, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'M22', '轻便二轮摩托车', 90, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'N11', '三轮汽车', 91, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'T11', '大型轮式拖拉机', 92, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'T20', '小型拖拉机', 93, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'T21', '小型轮式拖拉机', 94, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'T22', '手扶拖拉机', 95, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'T23', '手扶变形运输机', 96, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'J11', '轮式装载机械', 97, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'J12', '轮式挖掘机械', 98, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'J13', '轮式平地机械', 99, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G10', '重型全挂车', 100, '车辆类型代码类型');
COMMIT;
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G11', '重型普通全挂车', 101, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G12', '重型厢式全挂车', 102, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G13', '重型罐式全挂车', 103, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G14', '重型平板全挂车', 104, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G15', '重型集装箱全挂车', 105, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G16', '重型自卸全挂车', 106, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G17', '重型仓栅式全挂车', 107, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G18', '重型旅居全挂车', 108, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G19', '重型专项作业全挂车', 109, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G20', '中型全挂车', 110, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G21', '中型普通全挂车', 111, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G22', '中型厢式全挂车', 112, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G23', '中型罐式全挂车', 113, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G24', '中型平板全挂车', 114, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G25', '中型集装箱全挂车', 115, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G26', '中型自卸全挂车', 116, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G27', '中型仓栅式全挂车', 117, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G28', '中型旅居全挂车', 118, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G29', '中型专项作业全挂车', 119, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G30', '轻型全挂车', 120, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G31', '轻型普通全挂车', 121, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G32', '轻型厢式全挂车', 122, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G33', '轻型罐式全挂车', 123, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G34', '轻型平板全挂车', 124, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G35', '轻型自卸全挂车', 125, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G36', '轻型仓栅式全挂车', 126, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G37', '轻型旅居全挂车', 127, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'G38', '轻型专项作业全挂车', 128, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B10', '重型半挂车', 129, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B11', '重型普通半挂车', 130, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B12', '重型厢式半挂车', 131, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B13', '重型罐式半挂车', 132, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B14', '重型平板半挂车', 133, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B15', '重型集装箱半挂车', 134, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B16', '重型自卸半挂车', 135, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B17', '重型特殊结构半挂车', 136, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B18', '重型仓栅式半挂车', 137, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B19', '重型旅居半挂车', 138, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B1A', '重型专项作业半挂车', 139, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B1B', '重型低平板半挂车', 140, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B20', '中型半挂车', 141, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B21', '中型普通半挂车', 142, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B22', '中型厢式半挂车', 143, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B23', '中型罐式半挂车', 144, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B24', '中型平板半挂车', 145, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B25', '中型集装箱半挂车', 146, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B26', '中型自卸半挂车', 147, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B27', '中型特殊结构半挂车', 148, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B28', '中型仓栅式半挂车', 149, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B29', '中型旅居半挂车', 150, '车辆类型代码类型');
COMMIT;
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B2A', '中型专项作业半挂车', 151, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B2B', '中型低平板半挂车', 152, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B30', '轻型半挂车', 153, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B31', '轻型普通半挂车', 154, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B32', '轻型厢式半挂车', 155, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B33', '轻型罐式半挂车', 156, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B34', '轻型平板半挂车', 157, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B35', '轻型自卸半挂车', 158, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B36', '轻型仓栅式半挂车', 159, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B37', '轻型旅居半挂车', 160, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B38', '轻型专项作业半挂车', 161, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'B39', '轻型低平板半挂车', 162, '车辆类型代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2004, 'X99', '其他', 163, '车辆类型代码类型');
COMMIT;

--2005-机动车状态代码类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '2005', '机动车状态代码类型', -1, 'G(A/B)/T标准字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'A', '正常', 1, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'B', '转出', 2, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'C', '被盗抢', 3, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'D', '停驶', 4, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'E', '注销', 5, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'G', '违法未处理', 6, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'H', '海关监管', 7, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'I', '事故未处理', 8, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'J', '嫌疑车', 9, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'K', '查封', 10, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'L', '暂扣', 11, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'M', '强制注销', 12, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'N', '事故逃逸', 13, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'O', '锁定', 14, '机动车状态代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2005, 'Z', '其他', 15, '机动车状态代码类型');
COMMIT;

--2006-机动车号牌种类代码类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '2006', '机动车号牌种类代码类型', -1, 'G(A/B)/T标准字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '01', '大型汽车', 1, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '02', '小型汽车', 2, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '03', '使馆汽车', 3, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '04', '领馆汽车', 4, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '05', '境外汽车', 5, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '06', '外籍汽车', 6, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '07', '两、三轮摩托车', 7, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '08', '轻便摩托车', 8, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '09', '使馆摩托车', 9, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '10', '领馆摩托车', 10, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '11', '境外摩托车', 11, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '12', '外籍摩托车', 12, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '13', '农用运输车类', 13, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '14', '拖拉机', 14, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '15', '挂车', 15, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '16', '教练汽车', 16, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '17', '教练摩托车', 17, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '18', '试验汽车', 18, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '19', '试验摩托车', 19, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '20', '临时入境汽车', 20, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '21', '临时入境摩托车', 21, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '22', '临时行驶车', 22, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '23', '警用汽车号牌', 23, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '24', '警用摩托车号牌', 24, '机动车号牌种类代码类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 2006, '25', '军用车辆号牌', 25, '机动车号牌种类代码类型');
COMMIT;
--<<<<-G(A/B)/T标准字典类型//////////////////////////////////////////////////////

-->>>>-30~39-扩展字典类型////////////////////////////////////////////////////
--3001-身份信息比对返回值类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '3001', '身份信息比对返回值类型', -1, '扩展字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3001, '1', '验证通过', 1, '身份信息比对返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3001, '-1', '无预约信息', 2, '身份信息比对返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3001, '-2', '约考日期不是今天', 3, '身份信息比对返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3001, '-3', '已满当天允许考试次数', 4, '身份信息比对返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3001, '-4', '考生身份不合法', 5, '身份信息比对返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3001, '-5', '科目考试系统不合法', 6, '身份信息比对返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3001, '-6', '无考生分组信息', 7, '身份信息比对返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3001, '-7', '分组考官和考生不匹配', 8, '身份信息比对返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3001, '-8', '考场信息合法', 9, '身份信息比对返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3001, '-9', '考试员信息不合法', 10, '身份信息比对返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3001, '-10', '科目考试系统时间不合法', 11, '身份信息比对返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3001, '-90', '已进行了考试身份验证，无需重复验证！', 12, '身份信息比对返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3001, '$E', '系统异常', 13, '身份信息比对返回值类型');
COMMIT;

--3002-考试项目开始返回值类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '3002', '考试项目开始返回值类型', -1, '扩展字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '1', '数据写入成功', 1, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '0', '存在作弊嫌疑，已被取消或暂停考试', 2, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-1', '无考生身份比对信息', 3, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-2', '考试项目与考试安排信息不符', 4, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-3', '考试设备未备案', 5, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-4', '考试设备与考试项目不符', 6, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-5', '考试设备使用状态异常', 7, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-6', '考生考试车型与考试设备使用准驾车型范围不符', 8, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-7', '该考生存在作弊嫌疑，已被暂停/取消考试', 9, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-8', '项目开始时间不能小于科目开始时间', 10, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-9', '存在未结束的考试项目、不能开始新的项目考试！', 11, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-10', '科目三考车号牌不能为空', 12, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-11', '同一考车存在未结束考试，不能开始应用于新的考试', 13, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-12', '未找到考场记录', 14, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-13', '未找到考车信息', 15, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-14', '随机抽取考生的考车与当前考车不一致！', 16, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-15', '考试过程信息必须由考车上传', 17, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '-90', '考试项目已经开始，无需重传', 18, '考试项目开始返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3002, '$E', '系统异常', 19, '考试项目开始返回值类型');
COMMIT;

--3003-考试扣分返回值类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '3003', '考试扣分返回值类型', -1, '扩展字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3003, '1', '数据写入成功', 1, '考试扣分返回值类型') ;
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3003, '0', '已存在同一时间的同一扣分记录', 2, '考试扣分返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3003, '-1', '无当前考试项目开始信息', 3, '考试扣分返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3003, '-2', '扣分时间大于项目开始时间', 4, '考试扣分返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3003, '-3', '考试项目与扣分项不符', 5, '考试扣分返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3003, '-4', '项目考试过程中，请传入当前考试项目代码', 6, '考试扣分返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3003, '-5', '考生未进行身份认证', 7, '考试扣分返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3003, '-6', '扣分时间写入错误', 8, '考试扣分返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3003, '-7', '项目考试过程信息记录被非法篡改', 9, '考试扣分返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3003, '-12', '未找到考场记录', 10, '考试扣分返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3003, '-13', '未找到考车记录', 10, '考试扣分返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3003, '-15', '考试过程信息必须由考车上传', 11, '考试扣分返回值类型');
COMMIT;

--3004-考试过程图片返回值类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '3004', '考试过程图片返回值类型', -1, '扩展字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3004, '1', '数据写入成功', 1, '考试过程图片返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3004, '-1', '无当前考试项目开始信息', 2, '考试过程图片返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3004, '-2', '考生身份证明号码与考生预约信息不符', 3, '考试过程图片返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3004, '-3', '考试项目不正确', 4, '考试过程图片返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3004, '-4', '扣分时间写入错误', 5, '考试过程图片返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3004, '-90', '同一时间已传入抓拍照片', 6, '考试过程图片返回值类型');
COMMIT;

--3005-考试项目结束返回值类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '3005', '考试项目结束返回值类型', -1, '扩展字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '1', '数据写入成功', 1, '考试项目结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-1', '无当前考试项目开始信息', 2, '考试项目结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-2', '考生身份证明号码与考生预约信息不符', 3, '考试项目结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-3', '考试项目不正确', 4, '考试项目结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-4', '考试设备序号不正确！', 5, '考试项目结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-5', '考试项目结束时间写入错误', 6, '考试项目结束类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-6', '考生未进行身份认证', 7, '考试项目结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-7', '项目考试过程信息记录被非法篡改',8, '考试项目结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-8', '每个考试项目中必须至少抓拍一张照片', 9, '考试项目结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-9', '操作类型格式不正确', 10, '考试项目结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-12', '未找到考场记录', 11, '考试项目结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-13', '未找到考车信息', 12, '考试项目结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-15', '考试过程信息必须由考车上传', 13, '考试项目结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-90', '考试项目已经结束、无需重传', 14, '考试项目结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3005, '-91', '实际道路考试，在完成科目考试时统一结束',15, '考试项目结束返回值类型');
COMMIT;

--3006-考试科目考试结束返回值类型
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, -1, '3006', '考试科目考试结束返回值类型', -1, '扩展字典类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3006, '1', '数据写入成功', 1, '考试科目考试结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3006, '-1', '无当前科目考试信息', 2, '考试科目考试结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3006, '-2', '考生身份证明号码与考生预约信息不符', 3, '考试科目考试结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3006, '-3', '考试结束时间不正确', 4, '考试科目考试结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3006, '-4', '考试过程中拍摄照片数量少于3张', 5, '考试科目考试结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3006, '-5', '考试项目不符合要求', 6, '考试科目考试结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3006, '-6', '存在未结束的考试项目！', 7, '考试科目考试结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3006, '-7', '传输的考试成绩不可为空', 8, '考试科目考试结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3006, '-91', '考试成绩计算不一致', 9, '考试科目考试结束返回值类型');
INSERT INTO CFG_DICT
  (ID, DICT_TYPE, DICT_CODE, DICT_NAME, VIEW_INDEX, DICT_MEMO)
VALUES
  (SEQU_CFG_DICT_ID.NEXTVAL, 3006, '-92', '日间考试已结束等待进行夜间考试', 10, '考试科目考试结束返回值类型');
COMMIT;
--<<<<-扩展字典类型////////////////////////////////////////////////////////