/*
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '', '10000', '科目二通用评判', 0, 1);
--SEQU_CFG_ITEMS_ID.NEXTVAL: 序列
--'2'：科目(是科目几就写数据几)
--''：子父关系中父级代码,如无父代码则填写空
--'10000'：子代码,与父代码是继承关系
--'科目二通用评判'：名称
--0：扣分数
--1：级别,定义子父关系中的辈分
*/
--科目二通判扣100分
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '', '10000', '科目二通用评判', 0, 1);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10000', '10100', '不合格情形', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10101', '不按规定使用安全带或者戴安全头盔', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10102', '遮挡、关闭车内音视频监控设备', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10103', '不按考试员指令驾驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10104', '不能正确使用灯光、雨刮器等车辆常用操纵件', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10105', '启动发动机时挡位未置于空挡（驻车挡）', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10106', '起步时车辆后溜距离大于30cm', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10107', '不松驻车制动器起步,未及时纠正', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10108', '驾驶汽车双手同时离开转向盘', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10109', '使用挡位与车速长时间不匹配,造成车辆发动机转速过高或过低', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10110', '车辆在行驶中低头看挡或连续2次挂挡不进', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10111', '行驶中空挡滑行', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10112', '视线离开行驶方向超过2s', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10113', '违反交通安全法律、法规,影响交通安全', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10114', '不按交通信号灯、标志、标线或者交通警察指挥信号行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10115', '不按规定速度行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10116', '车辆行驶中骑轧车道中心实线或者车道边缘实线', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10117', '长时间骑轧车道分界线行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10118', '对可能出现危险的情形未采取减速、鸣喇叭等安全措施', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10119', '因观察、判断或者操作不当出现危险情况', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10120', '行驶中不能保持安全距离和安全车速', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10121', '行驶中身体任何部位伸出车外', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10122', '制动、加速踏板使用错误', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10123', '驾驶摩托车时手离开转向把', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10124', '二轮摩托车在行驶中左右摇摆或者脚触地', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10125', '摩托车制动时不同时使用前、后制动器', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10100', '10126', '考生未按照预约考试时间参加考试', 100, 3);
COMMIT;
--科目二通判扣10分
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10000', '10200', '扣10分情形', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10200', '10201', '启动发动机后,不及时松开启动开关', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10200', '10202', '不松驻车制动器起步,但能及时纠正', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10200', '10203', '驾驶姿势不正确', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10200', '10204', '起步时车辆后溜距离小于30cm', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10200', '10205', '操纵转向盘手法不合理', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10200', '10206', '起步或行驶中挂错挡,不能及时纠正', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10200', '10207', '转弯时,转、回方向过早、过晚,或者转向角度过大、过小', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10200', '10208', '换挡时发生齿轮撞击', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10200', '10209', '遇情况时不会合理使用离合器半联动控制车速', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10200', '10210', '因操作不当造成发动机熄火一次', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '10200', '10211', '制动不平顺', 10, 3);
COMMIT;
--科目二专项-倒车入库
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '', '20000', '科目二专项评判', 0, 1);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '20100', '倒车入库', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20100', '20101', '不按规定路线、顺序行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20100', '20102', '车身出线', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20100', '20103', '倒库不入', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20100', '20104', '在倒车前,未将两个前轮触地点均驶过控制线', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20100', '20105', '项目完成时间超过规定时间', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20100', '20106', '中途停车', 5, 3);
COMMIT;
--科目二专项-桩考
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '20200', '桩考', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20200', '20201', '不按规定路线、顺序行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20200', '20202', '碰擦桩杆', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20200', '20203', '车身出线,两轮摩托车轮出线', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20200', '20204', '倒库或移库不入', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20200', '20205', '项目完成时间超过规定时间', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20200', '20206', '中途停车', 5, 3);
COMMIT;
--科目二专项-坡道定点停车和起步
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '20300', '坡道定点停车和起步', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20300', '20301', '车辆停止后,汽车前保险杠或者摩托车前轴未定于桩杆线上,且前后超出50cm', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20300', '20302', '车辆停止后,车身距离路边缘线超出50cm', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20300', '20303', '车辆停止后,车身距离路边缘线超出50cm', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20300', '20304', '车辆停止后,汽车前保险杠或者摩托车前轴未定于桩杆线上,且前后不超出50cm', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20300', '20305', '车辆停止后,车身距离路边缘线超出30cm,未超出50cm', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20300', '20306', '停车后,未拉紧驻车制动器', 10, 3);
COMMIT;
--科目二专项-侧方停车
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '20400', '侧方停车', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20400', '20401', '车辆入库停止后,车身出线', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20400', '20402', '项目完成时间超过规定时间', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20400', '20403', '行驶中车轮触轧车道边线', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20400', '20404', '行驶中车身触碰库位边线', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20400', '20405', '出库时不使用或错误使用转向灯', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20400', '20406', '中途停车', 5, 3);
COMMIT;
--科目二专项-通过单边桥
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '20500', '通过单边桥', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20500', '20501', '其中有一车轮未上桥', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20500', '20502', '已骑上桥面,在行驶中出现一个车轮掉下桥面', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20500', '20503', '中途停车', 5, 3);
COMMIT;
--科目二专项-曲线行驶
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '20600', '曲线行驶', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20600', '20601', '车轮轧道路边缘线', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20600', '20602', '中途停车', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20600', '20603', '行驶时挡位未挂在二挡以上', 5, 3);
COMMIT;
--科目二专项-直角转弯
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '20700', '直角转弯', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20700', '20701', '车轮轧道路边缘线', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20700', '20702', '转弯时不使用或错误使用转向灯，转弯后不关闭转向灯', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20700', '20703', '中途停车', 5, 3);
COMMIT;
--科目二专项-通过限宽门
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '20800', '通过限宽门', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20800', '20801', '不按规定路线、顺序行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20800', '20802', '碰擦一次限宽门标杆', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20800', '20803', '车辆行驶速度低于10km/h', 10, 3);
COMMIT;
--科目二专项-通过连续障碍
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '20900', '通过连续障碍', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20900', '20901', '不按规定路线、顺序行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20900', '20902', '车轮轧道路边缘线', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20900', '20903', '中途停车', 5, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20900', '20904', '轧、碰、擦一个圆饼', 5, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20900', '20905', '行驶时挡位未挂在二挡以上', 5, 3);
COMMIT;
--科目二专项-起伏路行驶
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '21000', '起伏路行驶', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21000', '21001', '通过起伏路面时，车速控制不当，车辆严重跳跃', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21000', '21002', '中途停车', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21000', '21003', '通过起伏路面前不减速', 10, 3);
COMMIT;
--科目二专项-窄路掉头
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '21100', '窄路掉头', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21100', '21101', '三进二退未完成掉头', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21100', '21102', '车轮轧路边缘线', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21100', '21103', '项目完成时间超过规定时间', 100, 3);
COMMIT;
--科目二专项-模拟高速公路行驶
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '21200', '模拟高速公路行驶', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21200', '21201', '行驶中占用两条车道、应急车道或大型车辆前后100m均无其它车辆仍不靠右侧车道行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21200', '21202', '变道未开启转向灯或未观察后面情况', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21200', '21203', '驶入高速公路时，未提速至规定车速', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21200', '21204', '驶出高速公路时，未按照出口预告标志提前调整车速和车道', 100, 3);
COMMIT;
--科目二专项-模拟连续急弯山区路行驶
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '21300', '模拟连续急弯山区路行驶', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21300', '21301', '进入弯道前未减速至通过弯道所需的速度', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21300', '21302', '弯道内占用对方车道', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21300', '21303', '转弯过程中方向控制不稳，车轮轧弯道中心线或道路边缘线', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21300', '21304', '进入弯道前未鸣喇叭', 10, 3);
COMMIT;
--科目二专项-模拟隧道行驶
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '21400', '模拟隧道行驶', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21400', '21401', '驶抵隧道时未减速或未开启前照灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21400', '21402', '驶入隧道后不按规定车道行驶、变道', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21400', '21403', '驶抵隧道入（出）口时未鸣喇叭', 5, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21400', '21404', '驶出隧道后未关闭前照灯', 5, 3);
COMMIT;
--科目二专项-模拟雨（雾）天行驶
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '21500', '模拟雨（雾）天行驶', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21500', '21501', '雨天未开启或正确使用雨刮器', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21500', '21502', '雾天未开启雾灯、示廓灯、前照灯、危险报警闪光灯', 100, 3);
COMMIT;
--科目二专项-模拟湿滑路行驶
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '21600', '模拟湿滑路行驶', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21600', '21601', '未能使用低速挡平稳通过', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21600', '21602', '进入湿滑路前，未减速', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21600', '21603', '通过时急加速、急刹车', 100, 3);
COMMIT;
--科目二专项-模拟紧急情况处置（前方突然出现障碍物）
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '21700', '模拟紧急情况处置（前方突然出现障碍物）', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21700', '21701', '未及时制动', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21700', '21702', '停车后未开启危险报警闪光灯', 100, 3);
COMMIT;
--科目二专项-模拟紧急情况处置（高速公路车辆故障）
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '20000', '21800', '模拟紧急情况处置（高速公路车辆故障）', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21800', '21801', '未及时平稳靠边停车', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21800', '21802', '停车后未开启危险报警闪光灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21800', '21803', '未及时提示乘员疏散', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21800', '21804', '未正确摆放警告标志或未报警', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '2', '21800', '21805', '本人未撤离至护栏外侧', 100, 3);
COMMIT;
--科目三通判扣100分
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '', '30000', '科目三通用评判', 0, 1);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30000', '30100', '不合格情形', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30101', '不按规定使用安全带或者戴安全头盔', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30102', '遮挡、关闭车内音视频监控设备', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30103', '不按考试员指令驾驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30104', '不能正确使用灯光、雨刮器等车辆常用操纵件', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30105', '启动发动机时挡位未置于空挡（驻车挡）', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30106', '绿灯亮起后，前方无其他车辆、行人等影响通行时，10秒内未完成起步', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30107', '起步时车辆后溜距离大于30cm', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30108', '驾驶汽车双手同时离开转向盘', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30109', '单手控制转向盘时，不能有效、平稳控制行驶方向', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30110', '车辆行驶方向控制不准确，方向晃动，车辆偏离正确行驶方向', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30111', '不能根据交通情况合理选择行驶车道、速度', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30112', '使用挡位与车速长时间不匹配，造成车辆发动机转速过高或过低', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30113', '车辆在行驶中低头看挡或连续2次挂挡不进', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30114', '行驶中空挡滑行', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30115', '视线离开行驶方向超过2s', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30116', '违反交通安全法律、法规，影响交通安全', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30117', '不按交通信号灯、标志、标线或者交通警察指挥信号行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30118', '不按规定速度行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30119', '车辆行驶中骑轧车道中心实线或者车道边缘实线', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30120', '长时间骑轧车道分界线行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30121', '起步、转向、变更车道、超车、靠边停车前不使用或错误使用转向灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30122', '起步、转向、变更车道、超车、靠边停车前，开转向灯少于3s即转向', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30123', '争道抢行，妨碍其他车辆正常行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30124', '行驶中不能保持安全距离和安全车速', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30125', '连续变更两条或两条以上车道', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30126', '通过积水路面遇行人、非机动车时，有不减速等不文明驾驶行为', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30127', '遇行人通过人行横道不停车让行，不主动避让优先通行的车辆、行人、非机动车', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30128', '将车辆停在人行横道、网状线内等禁止停车区域', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30129', '行驶中身体任何部位伸出窗外', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30130', '制动、加速踏板使用错误', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30131', '对可能出现危险的情形未采取减速、鸣喇叭等安全措施', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30132', '因观察、判断或者操作不当出现危险情况', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30133', '驾驶摩托车时手离开转向把', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30134', '二轮摩托车在行驶中左右摇摆或者脚触地', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30135', '摩托车制动时不同时使用前、后制动器', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30100', '30136', '考生未按照预约考试时间参加考试', 100, 3);
COMMIT;
--科目三通判扣10分
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30000', '30200', '扣10分情形', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30200', '30201', '驾驶姿势不正确', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30200', '30202', '起步时车辆后溜，但后溜距离小于30cm', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30200', '30203', '操纵转向盘手法不合理', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30200', '30204', '起步或行驶中挂错挡，不能及时纠正', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30200', '30205', '转弯时，转、回方向过早、过晚，或者转向角度过大、过小', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30200', '30206', '换挡时发生齿轮撞击', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30200', '30207', '遇情况时不会合理使用离合器半联动控制车速', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30200', '30208', '因操作不当造成发动机熄火一次', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30200', '30209', '不能根据交通情况合理使用喇叭', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30200', '30210', '制动不平顺', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '30200', '30211', '遇后车发出超车信号，不按规定让行', 10, 3);
COMMIT;
--科目三专项-上车准备
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '', '40000', '科目三专项评判', 0, 1);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '40100', '上车准备', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40100', '40101', '未逆时针绕车一周检查车辆外观及周围环境', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40100', '40102', '打开车门前不观察后方交通情况', 100, 3);
COMMIT;
--科目三专项-起步
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '40200', '起步', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40200', '40201', '制动气压不足起步', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40200', '40202', '车门未完全关闭起步', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40200', '40203', '起步前，未观察内、外后视镜，回头观察后方交通情况', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40200', '40204', '启动发动机时，挡位未置于空挡（驻车挡）', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40200', '40205', '不松驻车制动器起步，未及时纠正', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40200', '40206', '不松驻车制动器起步，但能及时纠正', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40200', '40207', '发动机启动后，不及时松开启动开关', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40200', '40208', '道路交通情况复杂时起步不能合理使用喇叭', 5, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40200', '40209', '起步时车辆发生闯动', 5, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40200', '40210', '起步时，加速踏板控制不当，致使发动机转速过高', 5, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40200', '40211', '启动发动机前，不检查调整驾驶座椅、后视镜、检查仪表', 5, 3);
COMMIT;
--科目三专项-直线行驶
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '40300', '直线行驶', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40300', '40301', '方向控制不稳，不能保持车辆直线运行', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40300', '40302', '遇前车制动时不及时采取减速措施', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40300', '40303', '不适时通过内、外后视镜观察后方交通情况', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40300', '40304', '未及时发现路面障碍物或发现路面障碍物未及时采取减速措施', 10, 3);
COMMIT;
--科目三专项-加减挡位操作
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '40400', '加减挡位操作', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40400', '40401', '未按指令平稳加、减挡', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40400', '40402', '车辆运行速度和挡位不匹配', 10, 3);
COMMIT;
--科目三专项-变更车道
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '40500', '变更车道', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40500', '40501', '变更车道前，未通过内、外后视镜观察，并向变更车道方向回头观察后方道路交通情况', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40500', '40502', '变更车道时，判断车辆安全距离不合理，妨碍其他车辆正常行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40500', '40503', '变更车道时，控制行驶速度不合理，妨碍其他车辆正常行驶', 100, 3);
COMMIT;
--科目三专项-靠边停车
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '40600', '靠边停车', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40600', '40601', '停车前，不通过内、外后视镜观察后方和右侧交通情况，并回头观察确认安全', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40600', '40602', '考试员发出靠边停车指令后，未能在规定的距离内停车', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40600', '40603', '停车后，车身超过道路右侧边缘线或者人行道边缘', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40600', '40604', '需要下车的，在打开车门前不回头观察左后方交通情况', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40600', '40605', '下车后不关闭车门', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40600', '40606', '停车后，车身距离道路右侧边缘线或者人行道边缘超出50cm', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40600', '40607', '停车后，车身距离道路右侧边缘线或者人行道边缘超出30cm，未超出50cm', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40600', '40608', '停车后，未拉紧驻车制动器', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40600', '40609', '拉紧驻车制动器前放松行车制动踏板', 10, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40600', '40610', '下车前不将发动机熄火', 5, 3);
COMMIT;
--科目三专项-直行通过路口
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '40700', '直行通过路口', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40700', '40701', '不按规定减速或停车瞭望', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40700', '40702', '不观察左、右方交通情况', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40700', '40703', '不主动避让优先通行的车辆、行人、非机动车', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40700', '40704', '遇有路口交通阻塞时进入路口，将车辆停在路口内等候', 100, 3);
COMMIT;
--科目三专项-路口左转弯
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '40800', '路口左转弯', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40800', '40801', '不按规定减速或停车瞭望', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40800', '40802', '不观察左、右方交通情况，转弯通过路口时，未观察侧前方交通情况', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40800', '40803', '不主动避让优先通行的车辆、行人、非机动车', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40800', '40804', '遇有路口交通阻塞时进入路口，将车辆停在路口内等候', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40800', '40805', '左转通过路口时，未靠路口中心点左侧转弯', 10, 3);
COMMIT;
--科目三专项-路口右转弯
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '40900', '路口右转弯', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40900', '40901', '不按规定减速或停车瞭望', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40900', '40902', '不观察左、右方交通情况，转弯通过路口时，未观察侧前方交通情况', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40900', '40903', '不主动避让优先通行的车辆、行人、非机动车', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40900', '40904', '遇有路口交通阻塞时进入路口，将车辆停在路口内等候', 100, 3);
COMMIT;
--科目三专项-通过人行横道线
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '41000', '通过人行横道线', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41000', '41001', '不按规定减速慢行', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41000', '41002', '不观察左、右方交通情况', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41000', '41003', '未停车礼让行人', 100, 3);
COMMIT;
--科目三专项-通过学校区域
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '41100', '通过学校区域', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41100', '41101', '不按规定减速慢行', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41100', '41102', '不观察左、右方交通情况', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41100', '41103', '未停车礼让行人', 100, 3);
COMMIT;
--科目三专项-通过公共汽车站
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '41200', '通过公共汽车站', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41200', '41201', '不按规定减速慢行', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41200', '41202', '不观察左、右方交通情况', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41200', '41203', '未停车礼让行人', 100, 3);
COMMIT;
--科目三专项-会车
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '41300', '会车', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41300', '41301', '在没有中心隔离设施或者中心线的道路上会车时，不减速靠右行驶，或未与其他车辆、行人、非机动车保持安全距离', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41300', '41302', '会车困难时不让行', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41300', '41303', '横向安全间距判断差，紧急转向避让对方来车', 100, 3);
COMMIT;
--科目三专项-超车
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '41400', '超车', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41400', '41401', '超车前，不通过内、外后视镜观察后方和左侧交通情况并回头观察确认安全', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41400', '41402', '超车时机选择不合理，影响其他车辆正常行驶', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41400', '41403', '超车时，未回头观察被超越车辆动态', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41400', '41404', '超车时未与被超越车辆保持安全距离', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41400', '41405', '超车后，驶回原车道前，不通过内、外后视镜观察后方和右侧交通情况并回头观察确认安全', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41400', '41406', '在没有中心线或同方向只有一条行车道的道路上从右侧超车', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41400', '41407', '当后车发出超车信号时，具备让车条件不减速靠右让行', 10, 3);
COMMIT;
--科目三专项-掉头
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '41500', '掉头', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41500', '41501', '不能正确观察交通情况选择掉头时机', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41500', '41502', '掉头地点选择不当', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41500', '41503', '掉头前未开启左转向灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41500', '41504', '掉头时，妨碍正常行驶的其他车辆和行人通行', 10, 3);
COMMIT;
--科目三专项-夜间行驶
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '41600', '夜间行驶', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41600', '41601', '不能正确开启灯光', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41600', '41602', '同方向近距离跟车行驶时，使用远光灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41600', '41603', '通过急弯、坡路、拱桥、人行横道或者没有交通信号灯控制的路口时，不交替使用远近光灯示意', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41600', '41604', '会车时不按规定使用近光灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41600', '41605', '通过路口时使用远光灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41600', '41606', '超车时未交替使用远近光灯提醒被超越车辆', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41600', '41607', '在有路灯、照明良好的道路上行驶时，使用远光灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41600', '41608', '在路边临时停车不关闭前照灯或不开启示廓灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41600', '41609', '进入无照明、照明不良的道路行驶时不使用远光灯', 5, 3);
COMMIT;
--科目三专项-模拟夜间灯光考试
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '40000', '41700', '模拟夜间灯光考试', 0, 2);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41700', '41701', '不能正确开启灯光', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41700', '41702', '同方向近距离跟车行驶时，使用远光灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41700', '41703', '通过急弯、坡路、拱桥、人行横道或者没有交通信号灯控制的路口时，不交替使用远近光灯示意', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41700', '41704', '会车时不按规定使用近光灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41700', '41705', '通过路口时使用远光灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41700', '41706', '超车时未交替使用远近光灯提醒被超越车辆', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41700', '41707', '在有路灯、照明良好的道路上行驶时，使用远光灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41700', '41708', '在路边临时停车不关闭前照灯或不开启示廓灯', 100, 3);
INSERT INTO CFG_ITEMS(ID, SUBJECT, PARENT_CODE, ITEM_CODE, ITEM_NAME, DEDUCT_SCORE, GRADE)
VALUES(SEQU_CFG_ITEMS_ID.NEXTVAL, '3', '41700', '41709', '进入无照明、照明不良的道路行驶时不使用远光灯', 5, 3);
COMMIT;