//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.TMRIOutAccess {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://192.168.1.254:9080/monweb/services/TmriOutAccess", ConfigurationName="TMRIOutAccess.TmriJaxRpcOutAccess")]
    public interface TmriJaxRpcOutAccess {
        
        // CODEGEN: 消息 queryObjectOutRequest 的包装命名空间(http://endpoint.axis.framework.tmri.com)以后生成的消息协定与默认值(http://192.168.1.254:9080/monweb/services/TmriOutAccess)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Client.TMRIOutAccess.queryObjectOutResponse queryObjectOut(Client.TMRIOutAccess.queryObjectOutRequest request);
        
        // CODEGEN: 消息 writeObjectOutRequest 的包装命名空间(http://endpoint.axis.framework.tmri.com)以后生成的消息协定与默认值(http://192.168.1.254:9080/monweb/services/TmriOutAccess)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Client.TMRIOutAccess.writeObjectOutResponse writeObjectOut(Client.TMRIOutAccess.writeObjectOutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryObjectOut", WrapperNamespace="http://endpoint.axis.framework.tmri.com", IsWrapped=true)]
    public partial class queryObjectOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xtlb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string jkxlh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string jkid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string UTF8XmlDoc;
        
        public queryObjectOutRequest() {
        }
        
        public queryObjectOutRequest(string xtlb, string jkxlh, string jkid, string UTF8XmlDoc) {
            this.xtlb = xtlb;
            this.jkxlh = jkxlh;
            this.jkid = jkid;
            this.UTF8XmlDoc = UTF8XmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryObjectOutResponse", WrapperNamespace="http://192.168.1.254:9080/monweb/services/TmriOutAccess", IsWrapped=true)]
    public partial class queryObjectOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string queryObjectOutReturn;
        
        public queryObjectOutResponse() {
        }
        
        public queryObjectOutResponse(string queryObjectOutReturn) {
            this.queryObjectOutReturn = queryObjectOutReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="writeObjectOut", WrapperNamespace="http://endpoint.axis.framework.tmri.com", IsWrapped=true)]
    public partial class writeObjectOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string xtlb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string jkxlh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string jkid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string UTF8XmlDoc;
        
        public writeObjectOutRequest() {
        }
        
        public writeObjectOutRequest(string xtlb, string jkxlh, string jkid, string UTF8XmlDoc) {
            this.xtlb = xtlb;
            this.jkxlh = jkxlh;
            this.jkid = jkid;
            this.UTF8XmlDoc = UTF8XmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="writeObjectOutResponse", WrapperNamespace="http://192.168.1.254:9080/monweb/services/TmriOutAccess", IsWrapped=true)]
    public partial class writeObjectOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string writeObjectOutReturn;
        
        public writeObjectOutResponse() {
        }
        
        public writeObjectOutResponse(string writeObjectOutReturn) {
            this.writeObjectOutReturn = writeObjectOutReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TmriJaxRpcOutAccessChannel : Client.TMRIOutAccess.TmriJaxRpcOutAccess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TmriJaxRpcOutAccessClient : System.ServiceModel.ClientBase<Client.TMRIOutAccess.TmriJaxRpcOutAccess>, Client.TMRIOutAccess.TmriJaxRpcOutAccess {
        
        public TmriJaxRpcOutAccessClient() {
        }
        
        public TmriJaxRpcOutAccessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TmriJaxRpcOutAccessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TmriJaxRpcOutAccessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TmriJaxRpcOutAccessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.TMRIOutAccess.queryObjectOutResponse Client.TMRIOutAccess.TmriJaxRpcOutAccess.queryObjectOut(Client.TMRIOutAccess.queryObjectOutRequest request) {
            return base.Channel.queryObjectOut(request);
        }
        
        public string queryObjectOut(string xtlb, string jkxlh, string jkid, string UTF8XmlDoc) {
            Client.TMRIOutAccess.queryObjectOutRequest inValue = new Client.TMRIOutAccess.queryObjectOutRequest();
            inValue.xtlb = xtlb;
            inValue.jkxlh = jkxlh;
            inValue.jkid = jkid;
            inValue.UTF8XmlDoc = UTF8XmlDoc;
            Client.TMRIOutAccess.queryObjectOutResponse retVal = ((Client.TMRIOutAccess.TmriJaxRpcOutAccess)(this)).queryObjectOut(inValue);
            return retVal.queryObjectOutReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.TMRIOutAccess.writeObjectOutResponse Client.TMRIOutAccess.TmriJaxRpcOutAccess.writeObjectOut(Client.TMRIOutAccess.writeObjectOutRequest request) {
            return base.Channel.writeObjectOut(request);
        }
        
        public string writeObjectOut(string xtlb, string jkxlh, string jkid, string UTF8XmlDoc) {
            Client.TMRIOutAccess.writeObjectOutRequest inValue = new Client.TMRIOutAccess.writeObjectOutRequest();
            inValue.xtlb = xtlb;
            inValue.jkxlh = jkxlh;
            inValue.jkid = jkid;
            inValue.UTF8XmlDoc = UTF8XmlDoc;
            Client.TMRIOutAccess.writeObjectOutResponse retVal = ((Client.TMRIOutAccess.TmriJaxRpcOutAccess)(this)).writeObjectOut(inValue);
            return retVal.writeObjectOutReturn;
        }
    }
}
